
log_errors = On
error_log = /var/www/html/php-error.log
memory_limit = 256M
upload_max_filesize = 50M
post_max_size = 50M
max_execution_time = 30
date.timezone = "Europe/Paris"
session.save_path = "/tmp"
session.use_strict_mode = 1
session.cookie_secure = 0
session.cookie_httponly = 1

display_errors = On
display_startup_errors = On
error_reporting = E_ALL
