server {
    listen 8060
    
    server_name morbach.com

    root ./www
    index index.html

    client_max_body_size 10M

    error_page 403 /errors/403.html
    error_page 404 /errors/403.html
    error_page 405 /errors/405.html
    error_page 500 /errors/500.html
    error_page 503 /errors/503.html

    location /admin {
        root ./www
        index admin.html
        deny all
    }

    location /static/ {
        root ./www
        autoindex on
    }

    location /inconnu {
        return 302 https://fr.wikipedia.org/wiki/Les_Inconnus
    }

    location /cgi-bin {
		cgi_pass /usr/bin/php-cgi
		root ./www/cgi-bin
		index test_request.php
	}

	location /api {
		root ./www
		index api.html
		limit_except GET POST {
			deny all
		}
	}

	location /upload/ {
		root ./www/uploads
		client_max_body_size 50M
	}
}