server {
	listen 8080 
	listen 8070
	
	server_name moucham

	root ./www
	index index.html

	limit_except GET POST DELETE
	
	client_max_body_size 100M

	error_page 403 ./errors/403.html
	error_page 404 ./errors/404.html
	error_page 405 ./errors/405.html
	error_page 500 ./errors/500.html
	error_page 503 ./errors/503.html

	location /kapouet/ {
		root ./www/pouic/toto/
		index pouet.html
		limit_except GET	
	}

	location /admin/ {
		root ./www
		index admin.html
		limit_except GET
	}

	location /static/ {
		root ./www/static/
		autoindex on
		limit_except GET POST DELETE
	}

	location /test_autoindex/ {
		root ./www/test_autoindex/
		limit_except GET POST
		autoindex off
	}

	location /inconnu {
		return https://fr.wikipedia.org/wiki/Les_Inconnus
		limit_except GET
	}

	location /cgi-bin/ {
		cgi_pass /usr/bin/php
		root ./www/cgi-bin
		index test_cgi.php
		limit_except GET POST
	}

	location /api/ {
		root ./www
		index api.html
		limit_except GET
	}

	location /upload/ {
		root ./www/uploads
		client_max_body_size 50M
		limit_except POST
	}
}

server {
	listen 8090

	
	server_name test

	root ./contact
	index index.html
	limit_except GET POST DELETE
	client_max_body_size 10M

}